import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

// Java program to calculate MD5 hash value public class SHA {
public
static String getSHA(String input)
{
    try
    {

        // Static getInstance method is called with hashing MD5 MessageDigest hash = MessageDigest.getInstance("SHA-256");

        // digest() method is called to calculate message digest
        // of an input digest() return array of byte
        byte[] messageDigest = hash.digest(input.getBytes());

        // Convert byte array into signum representation BigInteger no = new BigInteger(1, messageDigest);

        // Convert message digest into hex value String hashtext = no.toString(16);
        while (hashtext.length() < 32)
        {
            hashtext = "0" + hashtext;
        }
        return hashtext;
    }

    // For specifying wrong message digest algorithms catch (NoSuchAlgorithmException e) {
    throw new RuntimeException(e);
}
}

// Driver code
public
static void main(String args[]) throws NoSuchAlgorithmException
{
    String s = "VVIT";
    System.out.println("Your HashCode Generated by SHA is: " + getSHA(s));
}
}
